//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на аблезговские
        ///аблезговский
        ///аблезговским
        ///аблезговскими
        ///аблезговских
        ///аблезговского
        ///аблезговском
        ///аблезговскому
        ///абраменковские
        ///абраменковский
        ///абраменковским
        ///абраменковскими
        ///абраменковских
        ///абраменковского
        ///абраменковском
        ///абраменковскому
        ///автогидроподъемник
        ///автогидроподъемника
        ///автогидроподъемникам
        ///автогидроподъемниками
        ///автогидроподъемниках
        ///автогидроподъемнике
        ///автогидроподъемники
        ///автогидроподъемников
        ///автогидроподъемником
        ///автогидроподъемнику
        ///автомассажер
        ///автомассажера
        ///автомассажерам
        ///автома [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string bases_constu {
            get {
                return ResourceManager.GetString("bases_constu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на аблёзговские
        ///аблёзговский
        ///аблёзговским
        ///аблёзговскими
        ///аблёзговских
        ///аблёзговского
        ///аблёзговском
        ///аблёзговскому
        ///абрамёнковские
        ///абрамёнковский
        ///абрамёнковским
        ///абрамёнковскими
        ///абрамёнковских
        ///абрамёнковского
        ///абрамёнковском
        ///абрамёнковскому
        ///автогидроподъёмник
        ///автогидроподъёмника
        ///автогидроподъёмникам
        ///автогидроподъёмниками
        ///автогидроподъёмниках
        ///автогидроподъёмнике
        ///автогидроподъёмники
        ///автогидроподъёмников
        ///автогидроподъёмником
        ///автогидроподъёмнику
        ///автомассажёр
        ///автомассажёра
        ///автомассажёрам
        ///автома [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string basesE_constu {
            get {
                return ResourceManager.GetString("basesE_constu", resourceCulture);
            }
        }
    }
}
